app = "fern-app-restless-shadow-7308"

[build]
  [build.args]
    NEXT_TELEMETRY_DISABLED = "1"

[env]
  PORT = "8080"
  HOSTNAME = "0.0.0.0"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = "stop"
  auto_start_machines = true
  min_machines_running = 0

[[vm]]
  memory = "512mb"
  cpu_kind = "shared"
  cpus = 1